# Generated by Django 5.2.8 on 2025-12-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_courses_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='courses',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='trainer_name',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
